SheilaWard_PortfolioMVC/ViewModels/EmailModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SheilaWard_PortfolioMVC.ViewModels
{
    public class EmailModel
    {
        [Required, Display(Name = "Name")]
        public String FromName { get; set; }

        [Required, Display(Name = "Email"), EmailAddress]
        public string FromEmail { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Body { get; set; }
    }
}

SheilaWard_PortfolioMVC/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SheilaWard_PortfolioMVC.Controllers
{
    public class ExercisesController : Controller
    {
        // GET: Exercises
        public ActionResult JSBasics()
        {
            return View();
        }
        public ActionResult Tester()
        {
            return View();
        }
    }
}

SheilaWard_PortfolioMVC/Controllers/HomeController.cs
using SheilaWard_PortfolioMVC.ViewModels;
using SheilaWard_PortfolioMVC.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace SheilaWard_PortfolioMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult GridDemo()
        {
            return View();
        }

        public ActionResult Add2Nums()
        {
            return View();
        }

        public ActionResult JavaScriptDemo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel email)
        {
            var from = $"{email.FromEmail}<{WebConfigurationManager.AppSettings["emailfrom"]}>";
            var mailMsg = new MailMessage(from, WebConfigurationManager.AppSettings["emailto"])
            {
                Subject = email.Subject,
                Body = email.Body,
                IsBodyHtml = true
            };
            var svc = new PersonalEmail();
            await svc.SendAsync(mailMsg);
            return RedirectToAction("Index");
        }
    }
}

SheilaWard_PortfolioMVC/Views/Exercises/Tester.cshtml
@{
    ViewBag.Title = "Tester";
}

<style>

    .newModal {
        width: 700px;
        height: 175px;
        font-weight: bold;
        font-size: 40 px;
        border-radius: 0;
    }
</style>
<br />
<br />
<div>

    <button class="btn btn-info btn-lg newModal">MATH</button><br />


    <button class="btn btn-warning btn-lg newModal">FACTORIAL</button><br />


    <button class="btn btn-primary btn-lg newModal">FIZZBUZZ</button><br />


    <button class="btn btn-success btn-lg newModal">PALINDROME</button><br />

</div>

@section scripts {
    <script>
        function FizzBuzzA(value1, value2) {
            let returnValue = "";
            for (let i = 1; i <= 100; i++) {
                if (i % value1 == 0 && i % value2 == 0) {
                    returnValue += 'FizzBuzz ';
                }
                else if (i % value1 == 0) {
                    returnValue += 'Fizz ';
                }
                else if (i % value2 == 0) {
                    returnValue += 'Buzz ';
                }
                else {
                    returnValue += i + ' ';
                }
            }
            return returnValue;
        }
           function check() {
               let output = "";
               let val1 = document.getElementById('fizzNum').value;
               let val2 = document.getElementById('buzzNum').value;
               output = FizzBuzzA(val1, val2);
               document.getElementById('fbResult').innerHTML = output;
           }
    </script>
}

SheilaWard_PortfolioMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SheilaWard_PortfolioMVC/Views/Home/Add2Nums.cshtml
@{
    ViewBag.Title = "Add2Nums";
}

<h2>Add2Nums</h2>
<div class="row">
    <div class="col-md-6">
        <p>Enter num1: <input id="num1" type="number" /></p>
        <p>Enter num2: <input id="num2" type="number" /></p>
        <button id="addBtn" class="btn btn-success">Add the Numbers</button>
    </div>
    <div class="col-md-6">
        <h3>Your two numbers added together are: </h3>
        <p id="sumOfNums"></p>
    </div>
    <hr />
</div>

@section scripts{
    <script>
        $("#addBtn").click(function () {
            var num1 = Number($("#num1").val());
            var num2 = +$("#num2").val();
            $("#sumOfNums").html(num1 + num2);
        })
    </script>
}

SheilaWard_PortfolioMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SheilaWard_PortfolioMVC/Views/Home/GridDemo.cshtml
@{
    ViewBag.Title = "GridDemo";
}

<style>
    .flex-container {
        display: flex;
        height: 400px;
        width: 800px;
    }

    .flex-container > div {
        font-size: 20px;
    }

    .cell-1 {
        display: flex;
        border: 1px solid dodgerblue;
        background-color: #f1f1f1;
        justify-content: center;
        align-items: center;
        height: 100px;
    }

    .cell-2 {
        display: flex;
        border: 1px solid dodgerblue;
        background-color: #f1f1f1;
        justify-content: center;
        align-items: center;
        height: 200px;
    }

    .cell-3 {
        display: flex;
        border: 1px solid dodgerblue;
        background-color: #f1f1f1;
        justify-content: center;
        align-items: center;
        height: 133px;
    }
</style>

<h2>Bootstrap Grid System (Column-Based)</h2>
<div class="container-fluid">
    <div class="col-md-4 h2">
        <div class="row">
            <div class="col-md-4">4</div>
            <div class="col-md-4">4</div>
            <div class="col-md-4">4</div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-6">6</div>
            <div class="col-md-6">6</div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-12">12</div>
        </div>
        <hr />
    </div>
    <div class="col-md-4 h3">
        <div class="row">
            <div class="col-md-3">3</div>
            <div class="col-md-3">3</div>
            <div class="col-md-3">3</div>
            <div class="col-md-3">3</div>
        </div>
        <hr />
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-8">8</div>
            <div class="col-md-4">4</div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-6">6</div>
            <div class="col-md-3">3</div>
            <div class="col-md-3">3</div>
        </div>
        <hr />
        <div class="row">
            <div class="col-md-2">2</div>
            <div class="col-md-3">3</div>
            <div class="col-md-2">2</div>
            <div class="col-md-3">3</div>
            <div class="col-md-2">2</div>
        </div>
        <hr />
        <div class="row">
            @for (var loop = 0; loop < 12; loop++)
            {
                <div class="col-md-1">1</div>
            }
        </div>
        <hr />
    </div>
</div>

<hr />

<h2>Bootstrap Grid System (Row-Based)</h2>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">1</div>
        <div class="col-md-9">2</div>
    </div>
    <div class="row h2">
        <div class="col-md-12">H2</div>
    </div>
    <div class="row">
        <div class="col-md-2">3</div>
        <div class="col-md-2">4</div>
        <div class="col-md-2">5</div>
        <div class="col-md-2">6</div>
        <div class="col-md-2">7</div>
        <div class="col-md-2">8</div>
    </div>
    <div class="row h3">
        <div class="col-md-12">H3</div>
    </div>
    <div class="row">
        @for (var loop = 9; loop <= 20; loop++)
        {
            <div class="col-md-1 table-bordered text-danger">@loop</div>
        }
    </div>
    <div class="row h4">
        <div class="col-md-3">H4</div>
        <div class="col-md-3">H4</div>
        <div class="col-md-6">H4</div>
    </div>
    <div class="row">
        <div class="col-md-3">21</div>
        <div class="col-md-3">22</div>
        <div class="col-md-6">23</div>
    </div>
</div>

<hr />

<h2>Bootstrap Grid System (Block-elements)</h2>
<div class="flex-container text-center">
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-6 cell-1">C1R1C1</div>
            <div class="col-md-6 cell-1">C1R1C2</div>
        </div>
        <div class="row">
            <div class="col-md-12 cell-1">C1R2C1</div>
        </div>
        <div class="row">
            <div class="col-md-6 cell-1">C1R3C1</div>
            <div class="col-md-6 cell-1">C1R3C2</div>
        </div>
        <div class="row">
            <div class="col-md-12 cell-1">C1R4C1</div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-12 cell-2">C2R1C1</div>
        </div>
        <div class="row">
            <div class="col-md-12 cell-2">C2R2C1</div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-12 cell-3">C3R1C1</div>
        </div>
        <div class="row">
            <div class="col-md-12 cell-3">C3R2C1</div>
        </div>
        <div class="row">
            <div class="col-md-12 cell-3">C3R3C1</div>
        </div>
    </div>
</div>

SheilaWard_PortfolioMVC/Views/Home/JavaScriptDemo.cshtml
@{
    ViewBag.Title = "JavaScriptDemo";
}

<h2>JavaScriptDemo</h2>

<h5>Enter 5 Numbers:</h5>
<input id="nbr1" type="number" name="nbr1" value="" />
<input id="nbr2" type="number" name="nbr2" value="" />
<input id="nbr3" type="number" name="nbr3" value="" />
<input id="nbr4" type="number" name="nbr4" value="" />
<input id="nbr5" type="number" name="nbr5" value="" />

<button class="btn btn-primary btn-lg">Click to Browse Statistics</button>
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Statistics for Number Group</h4>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
                    <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
                    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
                </ul>

                <div class="tab-content">
                    <div id="home" class="tab-pane fade in active">
                        <h3>HOME</h3>
                        <p>Some content.</p>
                    </div>
                    <div id="menu1" class="tab-pane fade">
                        <h3>Menu 1</h3>
                        <p>Some content in menu 1.</p>
                    </div>
                    <div id="menu2" class="tab-pane fade">
                        <h3>Menu 2</h3>
                        <p>Some content in menu 2.</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

SheilaWard_PortfolioMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Grid Demo", "GridDemo", "Home")</li>
                    <li>@Html.ActionLink("JS Basics", "JSBasics", "Exercises")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/SyntaxHighlighter/scripts/shCore.js"></script>
    @*add the other script tags for highlighter. Add the css at the top for highlighter*@
</body>
</html>